apiVersion: v1
kind: Pod
metadata:
  name: node-debugger
  namespace: kube-system
spec:
  hostPID: true
  hostNetwork: true
  serviceAccountName: debug-sa
  containers:
    - name: debugger
      image: alpine:3.19
      command: ["sleep", "infinity"]
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
